

site_name: My Docs
site_url: https://example.com
site_author: Martin Donath

# Repository
repo_name: syeda-git/mkdocs-sandbox
repo_url: https://github.com/syeda-git/mkdocs-sandbox
edit_uri: ""

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en

# Customization
extra:
    version:
        provider: mike
    alternate:
        - name: English
          link: /mkdocs-sandbox/9.5/
          link: /mkdocs-sandbox/10.0/
          lang: en
     
        - name: Francais
          link: /mkdocs-sandbox/9.5/fr/
          link: /mkdocs-sandbox/10.0/fr/
          lang: fr  
