site_name: My Docs
site_url: https://example.com/

theme: 
    name: material
    custom_dir: overrides

plugins:
    - search
    - include-markdown
    - macros

extra:
    prodname: HCL Volt MX
    os: linux

extra_css:
  - stylesheets/ssg-style.css
  
markdown_extensions:
    - pymdownx.caret
    - pymdownx.details
    
nav:
    - 'Introduction': 
        - About:    mydoc_about.md
        - Overview: mydoc_introduction.md
    - Topic1: topic1.md
    - Topic2: topic2.md
    - REST APIs: REST_APIs.md
    - Access: Access_Management_General\Access_Management.md
    - Popups Metrics: Access_Management_General\Guidelines_for_Pop-up_s_or_Alerts.md
    - Standard Metrics: Access_Management_General\StandardMetrics.md
    - Custom Metrics: Implementing_Custom_Metrics_in_VoltMX_Iris.md
    
  