#Project Information
site_name: HCL product name Help Center
site_description: >-
  A next-gen documentation site for HCL <product name>.
site_url: https://opensource.hcltechsw.com/product-name

# Theme Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono


  # Static files
  static_templates:
    - 404.html


# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HCL-TECH-SOFTWARE
  version:
    provider: mike
  
  consent:
    title: Cookie consent
    description: Hey there! Welcome to my cookie consent banner.
    cookies:
      analytics: 
        provider: google
        property: UA-169645537-2
    actions:
        - accept
        - manage


 # analytics:
  #  provider: google
   # property: UA-169645537-2

# Repository
repo_url: https://github.com/HCL-TECH-SOFTWARE/digital-experience
repo_name: hcl-software/digital-experience
edit_uri: edit/main/docs


# Customization
extra_css:
  - stylesheets/style.css

plugins:
  - search
  
 #Table of contents 
nav:
  - Home: index.md
  - About:   
     - Overview: introduction.md
  - Notices: notices.md